# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0

CONFIRMATION_MAX_TOKENS = 4096
CONFIRMATION_PATH_BATCH_SIZE = 8
AUTO_CONFIRMATION_MAX_PATHS = 48
AUTO_CONFIRMATION_MAX_ENDPOINTS = 12
AUTO_CONFIRMATION_PATHS_PER_ENDPOINT = 4

FINAL_ADJUDICATION_MAX_TOKENS = 6000
FINAL_DEDUP_BATCH_SIZE = 40
FINAL_DEDUP_REPRESENTATIVE_BATCH_SIZE = 120

FILE_FOCUS_MAX_SOURCE_TO_FILE_PATHS = 64
FILE_FOCUS_MAX_SOURCE_PATHS_PER_TARGET = 10
FILE_FOCUS_MAX_SOURCE_PATH_VARIANTS = 2
FILE_FOCUS_MAX_OUTGOING_CONTEXT_PATHS = 24
FILE_FOCUS_MAX_OUTGOING_PATHS_PER_TARGET = 4

FUNCTION_BODY_DEFAULT_CHARS = 3000
FUNCTION_BODY_SCAN_LINES = 300
FUNCTION_BODY_FALLBACK_LINES = 80

SOURCE_CONTEXT_MAX_TOTAL_CHARS = 60000
SOURCE_CONTEXT_PER_FUNCTION_CHARS = 3000

SUPPLEMENTARY_AUDIT_MAX_TOKENS = 8192
SUPPLEMENTARY_STRONG_MAX_TOKENS = 16384
SUPPLEMENTARY_CANDIDATE_MAX_TOTAL_CHARS = 50000
SUPPLEMENTARY_CANDIDATE_INTRA_PER_FUNCTION_CHARS = 5000
SUPPLEMENTARY_CANDIDATE_SEMANTIC_PER_FUNCTION_CHARS = 4000
SUPPLEMENTARY_GLOBAL_LIFECYCLE_MAX_TOTAL_CHARS = 50000
SUPPLEMENTARY_GLOBAL_LIFECYCLE_PER_FUNCTION_CHARS = 4000
SUPPLEMENTARY_GLOBALS_MAX_CHARS = 30000
SUPPLEMENTARY_LOCK_ORDER_BATCH_SIZE = 8
SUPPLEMENTARY_LOCK_ORDER_MAX_TOTAL_CHARS = 50000
SUPPLEMENTARY_LOCK_ORDER_PER_FUNCTION_CHARS = 5000
LOCK_ORDER_MAX_CONFLICTS = 40
SUPPLEMENTARY_INTRA_FUNCTION_BODY_CHARS = 4096
